const os = require('os');
console.log('My first app');
console.log(`File Name: ${__filename}`);
console.log(`Directory Name: ${__dirname}`);
// console.log(global);
// console.log(console);
// console.log(process);
// console.log(module);

console.log("=============== Built in Module - OS =======================");
console.log(`Arch: ${os.arch()}`);
// console.log(`Cpus: ${os.cpus()}`);
console.log(`Cpus:`,JSON.stringify(os.cpus(), null, 2));
console.log(`Freemem: ${os.freemem()}`);
console.log(`Totalmem: ${os.totalmem()}`);
console.log(`Hostname: ${os.hostname()}`);
console.log(`Plateform: ${os.platform()}`);
console.log(`Release: ${os.release()}`);
console.log(`Type: ${os.type()}`);
console.log(`Uptime: ${os.uptime()}`);
// console.log(`UserInfo: ${os.userInfo()}`);
console.log(`UserInfo:`, JSON.stringify(os.userInfo(), null, 2));
